graph TD
    b6abca8["Обновление после слияния"]
    0e4652d["Обновление 3 в ветке feature_branch"]
    d58b168["Обновление 2 в ветке feature_branch"]
    d8159fb["Обновление 1 в ветке feature_branch"]
    982498b["Обновление 3 в основной ветке"]
    ca93504["Обновление 2 в основной ветке"]
    3cb6267["Обновление 1 в основной ветке"]
    c484e16["Первый коммит в основной ветке"]
    0e4652d --> d58b168
    d58b168 --> d8159fb
    b6abca8 --> 982498b
    982498b --> ca93504
    ca93504 --> 3cb6267
    3cb6267 --> c484e16
    b6abca8 --> 0e4652d
    d8159fb  --> c484e16